
module.exports={
  KEYNAME_MARKETPRICES:'PRICES'
  , KEYNAME_KRWUSD:'KRWUSD'
  , POINTSKINDS:{C:1,S:1,K:1}
  , A_POINTSKINDS:['C','S','K']
  , TIMESTRFORMAT:'YYYY-MM-DD HH:mm:ss'
  , TIMESTRFORMATMILI:'HH:mm:ss.SSS ,YYYY-MM-DD '

}
// a={BTC:1,ETH:1,USDT:1,IOTC:1,MOKA:1,GAIA:1}